apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
- patch: |-
    - op: replace
      path: /metadata/namespace
      value: codefresh
  target:
    group: apps
    kind: Deployment
    version: v1
- patch: |-
    - op: replace
      path: /metadata/namespace
      value: codefresh
  target:
    kind: ServiceAccount
    version: v1
- patch: |-
    - op: replace
      path: /subjects/0/namespace
      value: codefresh
  target:
    group: rbac.authorization.k8s.io
    kind: ClusterRoleBinding
    version: v1
- patch: |-
    - op: replace
      path: /data/host
      value: "http://argocd-server.codefresh.svc.cluster.local"
  target:
    kind: ConfigMap
    version: v1
- patch: |-
    - op: replace
      path: /data/integration
      value: argocd-codefresh
  target:
    kind: ConfigMap
    version: v1
resources:
- https://raw.githubusercontent.com/codefresh-io/cli-v2/main/manifests/argo-agent/agent.yaml
